FROM node:25-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY next.config.ts dataSource.ts tsconfig.json eslint.config.mjs vitest.config.ts next-env.d.ts ./
COPY public ./public
COPY src ./src

CMD ["npm", "run", "dev"]
