source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "8.1.3.1"
gem "pg", "~> 1.5"
gem "puma", ">= 6.4"
gem "bootsnap", require: false
gem "omniauth", "~> 2.1"
gem "omniauth-rails_csrf_protection", "~> 2.0"
gem "omniauth-google-oauth2", "~> 1.2"
gem "google-cloud-storage", "~> 1.50"

group :development, :test do
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
